// textures.js — procedural canvas textures, with optional override from assets/textures/*.png
// (generated by scripts/gen-textures.mjs via gpt-image-2 if the owner runs it).
import * as THREE from 'three';

function cnv(w, h) {
  const c = document.createElement('canvas');
  c.width = w; c.height = h;
  return [c, c.getContext('2d')];
}
function speckle(ctx, w, h, n, colors, sizeMin = 1, sizeMax = 2.4) {
  for (let i = 0; i < n; i++) {
    ctx.fillStyle = colors[(Math.random() * colors.length) | 0];
    ctx.globalAlpha = 0.12 + Math.random() * 0.25;
    const s = sizeMin + Math.random() * (sizeMax - sizeMin);
    ctx.fillRect(Math.random() * w, Math.random() * h, s, s);
  }
  ctx.globalAlpha = 1;
}
function tex(canvas, repeatX = 1, repeatY = 1) {
  const t = new THREE.CanvasTexture(canvas);
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  t.repeat.set(repeatX, repeatY);
  t.colorSpace = THREE.SRGBColorSpace;
  t.anisotropy = 4;
  return t;
}

export function asphaltTexture(repeat = 8) {
  const [c, x] = cnv(256, 256);
  x.fillStyle = '#2b2f33'; x.fillRect(0, 0, 256, 256);
  speckle(x, 256, 256, 2600, ['#22262a', '#34393e', '#1d2124', '#3c4147', '#4a4f55']);
  // faint cracks
  x.strokeStyle = '#1a1d20'; x.globalAlpha = 0.5;
  for (let i = 0; i < 5; i++) {
    x.beginPath();
    let px = Math.random() * 256, py = Math.random() * 256;
    x.moveTo(px, py);
    for (let j = 0; j < 6; j++) { px += (Math.random() - .5) * 60; py += (Math.random() - .5) * 60; x.lineTo(px, py); }
    x.stroke();
  }
  x.globalAlpha = 1;
  return tex(c, repeat, repeat);
}

export function sandTexture(repeat = 6) {
  const [c, x] = cnv(256, 256);
  x.fillStyle = '#e8d9b4'; x.fillRect(0, 0, 256, 256);
  speckle(x, 256, 256, 2200, ['#d9c69a', '#f2e6c4', '#cbb689', '#fff3d6']);
  return tex(c, repeat, repeat);
}

export function grassTexture(repeat = 8) {
  const [c, x] = cnv(256, 256);
  x.fillStyle = '#3d7a44'; x.fillRect(0, 0, 256, 256);
  speckle(x, 256, 256, 3000, ['#356b3b', '#4a8c50', '#2e5f34', '#57a05e'], 1, 3);
  return tex(c, repeat, repeat);
}

export function waterTexture(repeat = 5) {
  const [c, x] = cnv(256, 256);
  const g = x.createLinearGradient(0, 0, 256, 256);
  g.addColorStop(0, '#1a8a8f'); g.addColorStop(.5, '#12777e'); g.addColorStop(1, '#1a8a8f');
  x.fillStyle = g; x.fillRect(0, 0, 256, 256);
  x.strokeStyle = '#7fd8d4'; x.lineWidth = 1.4;
  for (let i = 0; i < 26; i++) {
    x.globalAlpha = 0.1 + Math.random() * 0.2;
    const y = Math.random() * 256, w = 20 + Math.random() * 60;
    x.beginPath();
    x.moveTo(Math.random() * 256, y);
    x.quadraticCurveTo(Math.random() * 256, y - 4, Math.random() * 256 + w, y);
    x.stroke();
  }
  x.globalAlpha = 1;
  return tex(c, repeat, repeat);
}

// Parking lot surface: asphalt with painted slot stripes baked in, sized for the yard grid.
export function lotTexture(cols, rows, slotW, slotD) {
  const px = 64; // pixels per world unit-ish
  const [c, x] = cnv(cols * slotW * 8, rows * slotD * 8);
  const W = c.width, H = c.height;
  x.fillStyle = '#2b2f33'; x.fillRect(0, 0, W, H);
  speckle(x, W, H, W * H / 28, ['#22262a', '#34393e', '#3c4147']);
  x.strokeStyle = '#e8e4da'; x.lineWidth = 3; x.globalAlpha = 0.75;
  const sw = W / cols, sh = H / rows;
  for (let r = 0; r < rows; r++) for (let col = 0; col <= cols; col++) {
    x.beginPath();
    x.moveTo(col * sw, r * sh + sh * 0.12);
    x.lineTo(col * sw, r * sh + sh * 0.88);
    x.stroke();
  }
  x.globalAlpha = 1;
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace;
  t.anisotropy = 4;
  return t;
}

export function hazardTexture() {
  const [c, x] = cnv(128, 32);
  x.fillStyle = '#f5b301'; x.fillRect(0, 0, 128, 32);
  x.fillStyle = '#23282d';
  for (let i = -1; i < 8; i++) {
    x.beginPath();
    x.moveTo(i * 20, 32); x.lineTo(i * 20 + 12, 32); x.lineTo(i * 20 + 28, 0); x.lineTo(i * 20 + 16, 0);
    x.closePath(); x.fill();
  }
  return tex(c, 4, 1);
}

// Try to load an AI-generated texture; resolve with fallback if missing.
export function preferFile(name, fallbackTex) {
  return new Promise((resolve) => {
    const loader = new THREE.TextureLoader();
    loader.load(`assets/textures/${name}.png`,
      (t) => { t.wrapS = t.wrapT = THREE.RepeatWrapping; t.repeat.copy(fallbackTex.repeat); t.colorSpace = THREE.SRGBColorSpace; resolve(t); },
      undefined,
      () => resolve(fallbackTex));
  });
}
